version: '3.1'
services:
  mongo:
    image: mongo:latest
    container_name: mongo_wishlist
    hostname: mongo_wishlist
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=wishlist
      - MONGO_REPLICA_SET_NAME=rs0
    ports:
      - "27018:27017"
    expose:
      - 27018
    volumes:
      - ~/data/mongo:/data/db





